language: node_js
node_js:
  - "6"
cache: yarn
sudo: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - sudo chown -R root:root /opt/google/chrome/chrome-sandbox
  - sudo chmod -R 4775 /opt/google/chrome/chrome-sandbox
  - npm run test
